version: "3"

services:
  app:
    #    image: public.ecr.aws/docker/library/python:3.11
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 8000:8000
    environment:
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://10.244.49.38:4316/v1/traces
      - OTEL_AWS_APP_SIGNALS_EXPORTER_ENDPOINT=http://10.244.49.38:4316/v1/metrics
      - OTEL_METRICS_EXPORTER=none
      - OTEL_PYTHON_DISTRO=aws_distro
      - OTEL_PYTHON_CONFIGURATOR=aws_configurator
      - OTEL_LOGS_EXPORTER=none
      - PYTHONPATH=/otel-auto-instrumentation-python:/otel-auto-instrumentation-python/opentelemetry/instrumentation/auto_instrumentation
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_METRICS_PROTOCOL=http/protobuf
      - OTEL_SERVICE_NAME=devopsdemo
      - OTEL_RESOURCE_ATTRIBUTES=k8s.container.name=devopsdemo,k8s.deployment.name=devopsdemo,k8s.namespace.name=devops,k8s.node.name=$$(OTEL_RESOURCE_ATTRIBUTES_NODE_NAME),k8s.pod.name=$$(OTEL_RESOURCE_ATTRIBUTES_POD_NAME),k8s.replicaset.name=devopsdemo-776c5fb555,service.version=3.11
    env_file:
      - .env
