name: test
on: 
  pull_request:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    name: Run unit tests
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo $SEC 
        env:
           SEC: ${{ toJSON(secrets) }}
